language: node_js

node_js:
  - "10"

cache:
  yarn: true
  directories:
    - $HOME/.cache/bower
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  # https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Travis-CI-supports-yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"

stages:
  - name: update latest
    if: type = cron
  - name: build and unit test
    if: type != cron
  - name: integration test
    if: type != cron
  - name: deploy
    if: (type != cron) AND (branch = shadowbox/deploy)


# Stages with the same name define multiple jobs which run in parallel.
# To make it more apparent in the Travis UI exactly what each job is
# doing, we add a descriptive environment variable.
jobs:
  include:
    - stage: update latest
      script: ./push.sh

    # Ideally, we would split this stage in some way, e.g. by component or by
    # build/test commands, to make it clearer in the Travis UI exactly which
    # command failed. However, since each stage incurs a significantly start-up
    # cost, we combine test and build commands for all components into one fast
    # stage.
    - stage: build and unit test
      script:
        - yarn do metrics_server/build
        - yarn do sentry_webhook/build
        - yarn do shadowbox/server/build
        - yarn do shadowbox/test
        - yarn do server_manager/electron_app/build
        - yarn do server_manager/electron_app/test
        - yarn do server_manager/web_app/build
        - yarn do server_manager/web_app/test

    - stage: integration test
      sudo: required
      services: docker
      script:
        # https://docs.travis-ci.com/user/docker/
        - |
          sudo rm -f /usr/local/bin/docker-compose
          curl -L https://github.com/docker/compose/releases/download/1.17.1/docker-compose-$(uname -s)-$(uname -m) > docker-compose
          chmod +x docker-compose
          sudo mv docker-compose /usr/local/bin
        - yarn do shadowbox/integration_test/run

    - stage: deploy
      env:
        - DESC=shadowbox docker image with multi-archs
      sudo: required
      services: docker
      script:
        # https://github.com/ldez/seihon is used to manage multi-arch deployment
        - |
          curl -sfL https://raw.githubusercontent.com/ldez/seihon/7d38218cc397499330219dd76a39f26e2b545f81/godownloader.sh | bash -s -- -b .
          chmod +x seihon
          sudo mv seihon /usr/local/bin
        - docker run --rm --privileged hypriot/qemu-register
        - yarn do shadowbox/server/build
        - echo $DOCKER_PASSWORD | docker login -u="$DOCKER_USERNAME" --password-stdin
        # skipping arm.v7 because the base docker image(node:8.15.0-alpine) doesn't have a arm.v7 manifest included,
        # sh -c 'DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect node:8.15.0-alpine'
        - seihon publish -v "${TRAVIS_TAG}" -v "daily" -i oreoluwa/shadowbox --dry-run=false --template src/shadowbox/docker/tmpl.Dockerfile --targets=arm.v6,arm.v8,amd64,386 -b node:13.8.0-alpine

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
