name: "Daily Deploy"

on:
  push:
    branches:
      - shadowbox/deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Download Seihorn downloader
      run: |
        mkdir -p $GITHUB_WORKSPACE/.bin/seihon
        cd $GITHUB_WORKSPACE/.bin/seihon
        curl -sfL https://raw.githubusercontent.com/ldez/seihon/master/godownloader.sh | bash -s -- -b .
        echo "::add-path::$GITHUB_WORKSPACE/.bin/seihon"
        chmod +x seihon
    - name: Register qemu
      run: docker run --rm --privileged hypriot/qemu-register
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: Login to Docker Registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: seihon build and publish docker image
      env:
        DOCKER_BUILDKIT: 1
      run: |
        readonly IMAGE_TAG="daily-$(date +%Y-%m-%d)"
        readonly NODE_IMAGE="node:12.16.3-alpine"
        seihon publish -v "${IMAGE_TAG}" -v "daily" -i oreoluwa/shadowbox --dry-run=false --template src/shadowbox/docker/tmpl.Dockerfile --targets=arm.v6,arm.v7,arm.v8,amd64,386 -b ${NODE_IMAGE:-12.16.3-alpine}