name: "Daily Deploy"

on:
  push:
    branches:
      - shadowbox/deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Download Seihorn downloader
      run: |
        mkdir -p $GITHUB_WORKSPACE/.bin/seihon
        cd $GITHUB_WORKSPACE/.bin/seihon
        curl -sfL https://raw.githubusercontent.com/ldez/seihon/master/godownloader.sh | bash -s -- -b .
        echo "::add-path::$GITHUB_WORKSPACE/.bin/seihon"
        chmod +x seihon
    - name: Register qemu
      run: docker run --rm --privileged hypriot/qemu-register
    - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
    - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: do shadowbox/server/build
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: seihon build and publish docker image
      run: |
        readonly NODE_IMAGE="node@sha256:12b2154fb459fa5f42c54771524609db041e7ef3465935d0ca82940d2d72669d"
        seihon publish -v "${TRAVIS_TAG}" -v "daily" -i oreoluwa/shadowbox --dry-run=false --template src/shadowbox/docker/tmpl.Dockerfile --targets=arm.v6,arm.v7,arm.v8,amd64,386 -b ${NODE_IMAGE:-12.16.3-alpine}