name: "Daily Deploy"

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - shadowbox/deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: Checkout repo
      uses: actions/checkout@v2
    - uses: trilom/file-changes-action@v1.2.3
      id: get-file-changes
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          githubRepo: oreoluwa/outline-server
    - name: Check that Dockerfile was changed
      # if: contains(['push', 'pull_request'], github.event_name)
      id: checkmajorchange
      shell: python
      run: |
        import os
        import json

        file_path = os.environ['HOME'] + '/files.json'
        try:
          with open(file_path) as json_file:
            changes = json.load(json_file)
            dockerfiles = []
            for changed_file in changes:
              if 'Dockerfile' in changed_file:
                dockerfiles.append(changed_file)
            print("::set-output name=dockerfilechanged::{}".format(",".join(dockerfiles)))
        except:
          print('File {} not found'.format(file_path))
    - name: Notify of Dockerfile Changes
      uses: dawidd6/action-send-mail@v2
      if: contains(steps.checkmajorchange.outputs.dockerfilechanged, 'Dockerfile')
      with:
        server_address: smtp.sendgrid.net
        server_port: 587
        username: apikey
        password: ${{secrets.SENDGRID_PASSWORD}}
        subject: OutlineServer Dockerfile changed!
        body: |
          Hey,<br/>
          There has been a change in the Dockerfile for <a href="https://github.com/Jigsaw-Code/outline-server">outline-server</a>.<br/>
          Check it out and update the build process.<br/>
          For reference, here are the Dockerfiles changed:<br/>
          ${{ steps.checkmajorchange.outputs.dockerfilechanged }}<br/>
        to: ${{secrets.NOTIFICATION_EMAIL_ADDRESS}}
        from: ${{secrets.NOTIFICATION_SENDER_EMAIL_ADDRESS}}
        content_type: text/html 
    - name: Download Seihorn downloader
      run: |
        mkdir -p $GITHUB_WORKSPACE/.bin/seihon
        cd $GITHUB_WORKSPACE/.bin/seihon
        curl -sfL https://raw.githubusercontent.com/ldez/seihon/master/godownloader.sh | bash -s -- -b .
        echo "::add-path::$GITHUB_WORKSPACE/.bin/seihon"
        chmod +x seihon
    - name: Register qemu
      run: docker run --rm --privileged hypriot/qemu-register
    - name: Login to Docker Registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: seihon build and publish docker image
      env:
        DOCKER_BUILDKIT: 1
      run: |
        readonly IMAGE_TAG="daily-$(date +%Y-%m-%d)"
        readonly NODE_IMAGE="node:12.16.3-alpine"
        seihon publish -v "${IMAGE_TAG}" -v "daily" -i oreoluwa/shadowbox --dry-run=false --template src/shadowbox/docker/tmpl.Dockerfile --targets=arm.v6,arm.v7,arm.v8,amd64,386 -b ${NODE_IMAGE:-12.16.3-alpine}