name: "Experimental Deploy"

on:
  schedule:
  - cron: "0 */5 * * *"
  push:
    branches:
      - oreoluwa/experimental

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: Checkout repo
      uses: actions/checkout@v2
    - uses: lots0logs/gh-action-get-changed-files@2.1.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_REPOSITORY: oreoluwa/outline-server
    - name: Check that Dockerfile was changed
      id: checkmajorchange
      shell: python
      run: |
        import os
        import json

        file_path = os.environ['HOME'] + '/files.json'
        with open(file_path) as json_file:
          changes = json.load(json_file)
          dockerfiles = []
          for changed_file in changes:
            if 'Dockerfile' in changed_file:
              dockerfiles.append(changed_file)
          print("::set-output name=dockerfilechanged::{}".format(",".join(dockerfiles)))
    - name: Download Seihorn downloader
      run: |
        mkdir -p $GITHUB_WORKSPACE/.bin/seihon
        cd $GITHUB_WORKSPACE/.bin/seihon
        curl -sfL https://raw.githubusercontent.com/ldez/seihon/master/godownloader.sh | bash -s -- -b .
        echo "::add-path::$GITHUB_WORKSPACE/.bin/seihon"
        chmod +x seihon
    - name: Register qemu
      run: docker run --rm --privileged hypriot/qemu-register
    - name: Login to Docker Registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: seihon build and publish docker image
      env:
        DOCKER_BUILDKIT: 1
      run: |
        readonly IMAGE_TAG="experimental-$(date +%Y-%m-%d)"
        readonly NODE_IMAGE="node:12.16.3-alpine"
        seihon publish -v "${IMAGE_TAG}" -v "experimental" -i oreoluwa/shadowbox --dry-run=false --template src/shadowbox/docker/tmpl.Dockerfile --targets=arm.v6,arm.v7,arm.v8,amd64,386 -b ${NODE_IMAGE:-12.16.3-alpine}