name: Release Manager

on:
  push:
    tags:
      - "v[0-9]*"

env:
  SENTRY_DSN: https://533e56d1b2d64314bd6092a574e6d0f1@o74047.ingest.sentry.io/215496

jobs:
  release_manager:
    name: Release Manager
    runs-on: ${{ matrix.os }}
    environment: Production Outline Manager
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
      # Don't cancel jobs on other platforms if one fails
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16

      - name: Show Environment Info
        run: |
          npm -v
          openssl version
          env

      - name: Install Dependencies
        run: npm ci

      - name: Release Linux
        if: runner.os == 'Linux'
        run: npm run action server_manager/electron_app/release_linux

      - name: Release MacOS
        if: runner.os == 'macOS'
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          ENCRYPTED_SIGNING_CERT_IV: ${{ secrets.ENCRYPTED_SIGNING_CERT_IV }}
          ENCRYPTED_SIGNING_CERT_KEY: ${{ secrets.ENCRYPTED_SIGNING_CERT_KEY }}
        run: |
          openssl aes-256-cbc -K $ENCRYPTED_SIGNING_CERT_KEY -iv  $ENCRYPTED_SIGNING_CERT_IV -in macos-signing-certificate.p12.enc -out macos-signing-certificate.p12 -d -md sha256
          export CSC_LINK=$(pwd)/macos-signing-certificate.p12
          npm run action server_manager/electron_app/release_macos

      - name: Deploy
        uses: softprops/action-gh-release@v1
        with:
          files: "build/server_manager/electron_app/static/dist/*.*"
          draft: true
