name: CI


on:
  schedule:
  - cron: "* 23 * * *"

jobs:
  deploy:
    name: build
    runs-on: ubuntu-latest
    # timeout-minutes: 3
    steps:
    - uses: actions/checkout@v2
    - name: GitHub Sync to Upstream Repository
      uses: mheene/sync-upstream-repo@v0.1.2
      with:
      # GitHub public upstream repo
        upstream_repo: https://github.com/Jigsaw-Code/outline-server.git
    - name: Push newest changes to deploy branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: shadowbox/deploy
        force: true