name: CI

on:
  schedule:
  - cron: "0 0 * * *"
  push:
    branches:
      - master
      
jobs:
  scheduled:
    name: build
    runs-on: ubuntu-latest
    # timeout-minutes: 3
    steps:
    - uses: actions/checkout@v2
    - name: GitHub Sync to Upstream Repository
      uses: oreoluwa/github-repo-sync-upstream@1d9f00f
      with:
        source_repo: https://github.com/Jigsaw-Code/outline-server.git
        source_branch: master
        destination_branch: master
        strategy: rebase
    - name: Push newest changes to deploy branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: shadowbox/deploy
        force: true