name: CI

on:
  schedule:
  - cron: "30 * * * *"

jobs:
  scheduled:
    name: build
    runs-on: ubuntu-latest
    # timeout-minutes: 3
    steps:
    - name: GitHub Sync to Upstream Repository
      uses: oreoluwa/github-repo-sync-upstream@bf4f4c5
      with:
        source_repo: https://github.com/Jigsaw-Code/outline-server.git
        source_branch: master
        destination_branch: master
        strategy: merge
      env:
        FORCE_PUSH: "false"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
    - name: Push newest changes to deploy branch
      uses: ad-m/github-push-action@master
      with:
        directory: work
        github_token: ${{ secrets.PUSH_TOKEN }}
        branch: shadowbox/deploy
        force: true