name: Experimental

on:
  schedule:
  - cron: "0 */5 * * *"
  push:
    branches:
      - master

jobs:
  scheduled:
    name: build
    runs-on: ubuntu-latest
    # timeout-minutes: 3
    steps:
    - uses: actions/checkout@v2
    - name: GitHub Sync to Upstream Repository
      uses: oreoluwa/github-repo-sync-upstream@1d9f00f
      with:
        source_repo: https://github.com/Jigsaw-Code/outline-server.git
        source_branch: master
        destination_branch: oreoluwa/experimental
        strategy: merge