name: Experimental

on:
  push:
    branches:
      - master

jobs:
  scheduled:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Sync to Upstream Repository
      uses: oreoluwa/github-repo-sync-upstream@bf4f4c548f9e4ca0049e79ed8a45a0620e911000
      with:
        source_repo: https://github.com/Jigsaw-Code/outline-server.git
        source_branch: master
        destination_branch: oreoluwa/experimental
        strategy: merge
      env:
        FORCE_PUSH: "false"
        GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}    
