name: Build and Test

on: 
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize


jobs:
  manager:
    name: Build and Test

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # This matches the Ubuntu version used in our Travis releases
        os: [ubuntu-20.04]
      # Don't cancel jobs on other platforms if one fails
      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          cache: npm
          node-version: 16

      - name: Install dependencies
        run: NODE_DTRACE_PROVIDER_REQUIRE=hard npm ci

      - name: Lint
        run: npm run lint

      - name: Manager
        run: |
          SENTRY_DSN='test' npm run action server_manager/electron_app/release_linux
          npm run action server_manager/test

      - name: Shadowbox
        if: runner.os == 'Linux'
        run: |
          npm run action shadowbox/server/build
          npm run action shadowbox/test
          npm run action shadowbox/integration_test/start

      - name: Metrics Server
        if: runner.os == 'Linux'
        run: |
          npm run action metrics_server/build
          npm run action metrics_server/test

